sudo: false
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/pre-commit

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

language: python

stages:
  - linting
  - test

python:
  - "2.7"

jobs:
  include:
    - stage: linting
      name: "Pre-Commit"
      python: 3.6
      install: pip install pre_commit
      script: pre-commit run --all
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="odoo/odoo"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="OCA/OCB"

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" MQT_DEP="PIP"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
